### model
model_name_or_path: /jfs/qwen_models/Qwen2.5-VL-7B-Instruct
image_max_pixels: 12845056
video_max_pixels: 3136
trust_remote_code: true
use_fast_tokenizer: false

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
freeze_language_model: false  # choices: [true, false]
deepspeed: ./examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: describe_anything
dataset_dir: ./data
media_dir: ./data/data
template: qwen2_vl
cutoff_len: 8192
# max_samples: 10
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 16
streaming: true
buffer_size: 2
preprocessing_batch_size: 2

### output
output_dir: /data1/saves/qwen2_5vl-7b/full/qwen_seg
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard


### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# resume_from_checkpoint: /data1/saves/qwen2_5vl-7b/full/debug/checkpoint-21000
flash_attn: fa2
gradient_checkpointing: true
max_steps: 50000
save_total_limit: 2
# weight_decay: 0.01
accelerator_config:
  dispatch_batches: false
ignore_data_skip: true
add_tokens: ./examples/train_full/add_tokens_seg.txt
seed: 99999
dataloader_drop_last: true
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
