### model
model_name_or_path: /DATA/disk0/Qwen2.5-Omni-7B
image_max_pixels: 12845056
video_max_pixels: 16384
trust_remote_code: true
use_fast_tokenizer: false

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
freeze_language_model: false  # choices: [true, false]
deepspeed: ./examples/deepspeed/ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
# dataset: unitree,unitree_g1_instruct,glaive_toolcall_en_demo_audio,glaive_toolcall_zh_demo_audio
# dataset: unitree,unitree_g1_instruct,glaive_toolcall_en_demo_audio,glaive_toolcall_zh_demo_audio,glaive_toolcall_en_demo
dataset: mix_all
dataset_dir: ./data
media_dir: ./data/data
template: qwen2_omni
cutoff_len: 32768
# max_samples: 10
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 6
mix_strategy: interleave_over
streaming: true
buffer_size: 256
preprocessing_batch_size: 256

### output
output_dir: /DATA/disk0/saves/qwen2_omni-7b/full/unitree_train_long_conversations_32k_long_50ksteps
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: /DATA/disk0/saves/qwen2_omni-7b/full/unitree_train_long_conversations_32k_long_50ksteps/checkpoint-11000
flash_attn: fa2
gradient_checkpointing: true
max_steps: 50000
save_total_limit: 2
# weight_decay: 0.01
accelerator_config:
  dispatch_batches: false
ignore_data_skip: true

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
